version: '{build}'

clone_folder: C:\Projects\go\src\github.com\billziss-gh\cgofuse

environment:
  GOPATH: C:\Projects\go
  
install:
- choco install winfsp -y

build_script:
- set PATH=C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH%
- set CPATH=C:\Program Files (x86)\WinFsp\inc\fuse
- go install -v go install -v ./fuse ./examples/memfs ./examples/hellofs
